excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://joeSaad.github.io
title: GeekBlock
email: yousseffhs@yahoo.com
author: Joe Saad
description: This is a geek block; learn, experiment, create and share .. 
paginate: 3
google_analytics: 